pipeline1:
  on:
    push:
      branches:
        - main
        - develop
    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '16.13.0'

          - name: Install CLI
            run: npm i

          - name: Build
            run: npm run build

  # Definizione della seconda pipeline
pipeline2:
  on:
    push:
      branches:
        - main
        - develop
    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '16.13.0'

          - name: Install prettier
            run: npm i prettier

          - name: Build
            run: npm run prettier
