name: Build Application

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: Install CLI
        run: npm i @angular/cli

      - name: Build
        run: npm run build